# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import federated_pb2 as federated__pb2


class TrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTrain = channel.unary_unary(
                '/federated.Trainer/StartTrain',
                request_serializer=federated__pb2.TrainRequest.SerializeToString,
                response_deserializer=federated__pb2.TrainReply.FromString,
                )
        self.SendModel = channel.unary_unary(
                '/federated.Trainer/SendModel',
                request_serializer=federated__pb2.SendModelRequest.SerializeToString,
                response_deserializer=federated__pb2.SendModelReply.FromString,
                )
        self.HeartBeat = channel.unary_unary(
                '/federated.Trainer/HeartBeat',
                request_serializer=federated__pb2.Request.SerializeToString,
                response_deserializer=federated__pb2.HeartBeatResponse.FromString,
                )


class TrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTrain(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTrain': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrain,
                    request_deserializer=federated__pb2.TrainRequest.FromString,
                    response_serializer=federated__pb2.TrainReply.SerializeToString,
            ),
            'SendModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=federated__pb2.SendModelRequest.FromString,
                    response_serializer=federated__pb2.SendModelReply.SerializeToString,
            ),
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=federated__pb2.Request.FromString,
                    response_serializer=federated__pb2.HeartBeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.Trainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Trainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Trainer/StartTrain',
            federated__pb2.TrainRequest.SerializeToString,
            federated__pb2.TrainReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Trainer/SendModel',
            federated__pb2.SendModelRequest.SerializeToString,
            federated__pb2.SendModelReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Trainer/HeartBeat',
            federated__pb2.Request.SerializeToString,
            federated__pb2.HeartBeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
