# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"9\n\x0cTrainRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\r\n\x05world\x18\x03 \x01(\x05\"\x1d\n\nTrainReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x10SendModelRequest\x12\r\n\x05model\x18\x01 \x01(\t\"\x1f\n\x0eSendModelReply\x12\r\n\x05reply\x18\x01 \x01(\t2\x90\x01\n\x07Trainer\x12>\n\nStartTrain\x12\x17.federated.TrainRequest\x1a\x15.federated.TrainReply\"\x00\x12\x45\n\tSendModel\x12\x1b.federated.SendModelRequest\x1a\x19.federated.SendModelReply\"\x00\x42\x34\n\x1aio.grpc.examples.federatedB\x0e\x46\x65\x64\x65ratedProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_TRAINREQUEST = DESCRIPTOR.message_types_by_name['TrainRequest']
_TRAINREPLY = DESCRIPTOR.message_types_by_name['TrainReply']
_SENDMODELREQUEST = DESCRIPTOR.message_types_by_name['SendModelRequest']
_SENDMODELREPLY = DESCRIPTOR.message_types_by_name['SendModelReply']
TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:federated.TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)

TrainReply = _reflection.GeneratedProtocolMessageType('TrainReply', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREPLY,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:federated.TrainReply)
  })
_sym_db.RegisterMessage(TrainReply)

SendModelRequest = _reflection.GeneratedProtocolMessageType('SendModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMODELREQUEST,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:federated.SendModelRequest)
  })
_sym_db.RegisterMessage(SendModelRequest)

SendModelReply = _reflection.GeneratedProtocolMessageType('SendModelReply', (_message.Message,), {
  'DESCRIPTOR' : _SENDMODELREPLY,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:federated.SendModelReply)
  })
_sym_db.RegisterMessage(SendModelReply)

_TRAINER = DESCRIPTOR.services_by_name['Trainer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032io.grpc.examples.federatedB\016FederatedProtoP\001\242\002\003HLW'
  _TRAINREQUEST._serialized_start=30
  _TRAINREQUEST._serialized_end=87
  _TRAINREPLY._serialized_start=89
  _TRAINREPLY._serialized_end=118
  _SENDMODELREQUEST._serialized_start=120
  _SENDMODELREQUEST._serialized_end=153
  _SENDMODELREPLY._serialized_start=155
  _SENDMODELREPLY._serialized_end=186
  _TRAINER._serialized_start=189
  _TRAINER._serialized_end=333
# @@protoc_insertion_point(module_scope)
