# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"9\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\r\n\x05world\x18\x03 \x01(\x05\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x10SendModelRequest\x12\r\n\x05model\x18\x01 \x01(\t\"\x1f\n\x0eSendModelReply\x12\r\n\x05reply\x18\x01 \x01(\t2\x92\x01\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12G\n\tSendModel\x12\x1c.helloworld.SendModelRequest\x1a\x1a.helloworld.SendModelReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_SENDMODELREQUEST = DESCRIPTOR.message_types_by_name['SendModelRequest']
_SENDMODELREPLY = DESCRIPTOR.message_types_by_name['SendModelReply']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

SendModelRequest = _reflection.GeneratedProtocolMessageType('SendModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMODELREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.SendModelRequest)
  })
_sym_db.RegisterMessage(SendModelRequest)

SendModelReply = _reflection.GeneratedProtocolMessageType('SendModelReply', (_message.Message,), {
  'DESCRIPTOR' : _SENDMODELREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.SendModelReply)
  })
_sym_db.RegisterMessage(SendModelReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _HELLOREQUEST._serialized_start=32
  _HELLOREQUEST._serialized_end=89
  _HELLOREPLY._serialized_start=91
  _HELLOREPLY._serialized_end=120
  _SENDMODELREQUEST._serialized_start=122
  _SENDMODELREQUEST._serialized_end=155
  _SENDMODELREPLY._serialized_start=157
  _SENDMODELREPLY._serialized_end=188
  _GREETER._serialized_start=191
  _GREETER._serialized_end=337
# @@protoc_insertion_point(module_scope)
